

spring.application.name=security
server.port=${port:3000}

spring.messages.basename=messages/

security.whitelist=127.0.0.1, localhost


access-token.private=jdkfdfaekroemvkvkfd
access-token.public=mnvmckworeiofkfklkf
refresh-token.private=pqowpecvmwrcvkjf
refresh-token.public=urytnjfgmvfgmcghvmc

app.jwt.token_prefix=Bearer
app.jwt.secret_key=QWEOERK2O32FMXOERM3423KO34K
#24 * 60 * 60 * 1000
app.jwt.valid_time_token=86400000
#3 * 24 * 60 * 60 * 1000
app.jwt.valid_time_refresh_token=259200000
#5 * 60 * 1000
app.jwt.valid_time_reset_key=300000


#local H2DB
spring.datasource.url=jdbc:h2:file:./data
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2
spring.h2.console.settings.web-allow-others=true


# email sender
app.mail.emailFrom=halo.nguyen91@gmail.com

spring.mail.host=smtp.gmail.com
spring.mail.port=587
# ${MAIL_USERNAME}
spring.mail.username=halo.nguyen91
# ${MAIL_PASSWORD}
spring.mail.password=blmykbsbyyplrvlt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# logging root logger and appender file and stdout
log4j.rootLogger=DEBUG, stdout, file

# print info log into console
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.Threshold=debug
log4j.appender.stdout.Target=System.out
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L %m%n

# print info log into file
log4j.appender.file=org.apache.log4j.RollingFileAppender
log4j.appender.file.File=./files/mylog.log
log4j.appender.file.Threshold=debug
log4j.appender.file.MaxFileSize=5MB
log4j.appender.file.MaxBackupIndex=10
log4j.appender.file.layout=org.apache.log4j.PatternLayout
log4j.appender.file.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L %m%n